# Seminar 1

###  Intro to jupyter

In [9]:
print(1)

1


In [7]:
x = 1
x

1

In [8]:
print("x:", x)

x: 1


### Numpy

In [10]:
import numpy as np

#### Creating matrix / vector

In [11]:
matrix = np.zeros((5, 10)) # np.ones, np.empty

In [12]:
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.random.randint(100, size=(5, 10))

array([[ 7,  8,  4, 45, 69, 16, 46,  2, 67, 22],
       [ 9, 52, 16, 10, 31, 56, 62, 44, 80, 64],
       [55, 25, 85, 18, 75, 58, 50, 13, 49, 16],
       [44, 20, 16, 88, 37, 47, 45, 50, 55, 47],
       [39, 89, 53, 76, 19, 14, 61, 23, 25, 79]])

In [16]:
np.random.rand(5, 10)

array([[0.99812302, 0.17845019, 0.55142564, 0.34734815, 0.09887403,
        0.44626557, 0.66796179, 0.24488867, 0.68117054, 0.22193185],
       [0.74305593, 0.39732113, 0.34057203, 0.49419306, 0.35603076,
        0.49023536, 0.20120889, 0.52024386, 0.09220342, 0.83552312],
       [0.70871739, 0.97784696, 0.0727891 , 0.13831564, 0.9985749 ,
        0.64281499, 0.82218427, 0.19024651, 0.32675728, 0.19821504],
       [0.18650198, 0.83133376, 0.72421392, 0.50611794, 0.27570563,
        0.22271099, 0.43992701, 0.46739597, 0.65528171, 0.62756279],
       [0.97277589, 0.50062135, 0.54097054, 0.30490911, 0.39014163,
        0.43309306, 0.28963284, 0.120004  , 0.54030018, 0.58731777]])

In [19]:
lists = [[26, 1, 0], [5, 13, 5], [18, 3, 1], [13, 10, 0]]
data = np.array(lists)

In [21]:
?np.array

In [20]:
data

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0]])

In [22]:
data.shape

(4, 3)

In [23]:
data.dtype

dtype('int32')

In [24]:
vec = np.arange(5)
print(vec)
print(vec.shape)

[0 1 2 3 4]
(5,)


In [25]:
vec

array([0, 1, 2, 3, 4])

In [28]:
np.zeros((3, 2, 7)).shape

(3, 2, 7)

#### Операции

*  поэлементные
* матричные
* агрегирующие

In [29]:
# element-wise
data + data

array([[52,  2,  0],
       [10, 26, 10],
       [36,  6,  2],
       [26, 20,  0]])

In [30]:
data * data

array([[676,   1,   0],
       [ 25, 169,  25],
       [324,   9,   1],
       [169, 100,   0]])

In [31]:
data ** 2

array([[676,   1,   0],
       [ 25, 169,  25],
       [324,   9,   1],
       [169, 100,   0]], dtype=int32)

In [32]:
a = np.arange(12).reshape(3, 4)
b = np.zeros((3, 4))
a * b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
a + b

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [35]:
np.exp(data)

array([[1.95729609e+11, 2.71828183e+00, 1.00000000e+00],
       [1.48413159e+02, 4.42413392e+05, 1.48413159e+02],
       [6.56599691e+07, 2.00855369e+01, 2.71828183e+00],
       [4.42413392e+05, 2.20264658e+04, 1.00000000e+00]])

In [36]:
### aggregate
np.sum(data)

95

In [37]:
np.sum(data, axis=1) # сколько студентов в группе - по каждому вопросу

array([27, 23, 22, 23])

In [38]:
np.sum(data, axis=0) # сколько ответов на вопросы

array([62, 27,  6])

In [39]:
np.prod(a, axis=1)

array([   0,  840, 7920])

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
np.mean(data, axis=0)

array([15.5 ,  6.75,  1.5 ])

In [43]:
### matrix operations
x = np.random.rand(3, 4)
y = np.random.rand(4, 10)
np.dot(x, y)

array([[1.01988216, 0.61729898, 0.31315012, 1.26217266, 0.93020545,
        1.11228739, 1.4003831 , 1.18123294, 0.65644658, 0.6913863 ],
       [1.04816856, 0.85631929, 0.69167714, 1.53843057, 1.13610617,
        1.72464943, 1.50183736, 1.36307135, 0.93858079, 0.75331124],
       [1.21677902, 0.95566282, 1.01035741, 1.69394752, 0.88672432,
        1.81695108, 1.38432387, 1.29044796, 0.8028769 , 0.53534744]])

In [44]:
x @ y

array([[1.01988216, 0.61729898, 0.31315012, 1.26217266, 0.93020545,
        1.11228739, 1.4003831 , 1.18123294, 0.65644658, 0.6913863 ],
       [1.04816856, 0.85631929, 0.69167714, 1.53843057, 1.13610617,
        1.72464943, 1.50183736, 1.36307135, 0.93858079, 0.75331124],
       [1.21677902, 0.95566282, 1.01035741, 1.69394752, 0.88672432,
        1.81695108, 1.38432387, 1.29044796, 0.8028769 , 0.53534744]])

In [45]:
v = np.ones(3)
np.dot(data, v) # (4, 3) x (3,) -> (4,)

array([27., 23., 22., 23.])

In [46]:
v.shape

(3,)

In [47]:
v = np.ones((3, 1))
np.dot(data, v) # (4, 3) x (3, 1) -> (4, 1)

array([[27.],
       [23.],
       [22.],
       [23.]])

In [48]:
data @ v

array([[27.],
       [23.],
       [22.],
       [23.]])

In [49]:
data.dot(v)

array([[27.],
       [23.],
       [22.],
       [23.]])

In [ ]:
np.sum(data, axis=1)
data.sum(axis=1)

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [50]:
np.linalg.inv(np.eye(5)) # обратная матрица

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [-0., -0., -0.,  1., -0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [ ]:
np.linalg.solve()

#### Indexing

In [53]:
data[1]

array([ 5, 13,  5])

In [54]:
data[:, 2]

array([0, 5, 1, 0])

In [55]:
data[:2, :2]

array([[26,  1],
       [ 5, 13]])

In [56]:
data[::2]

array([[26,  1,  0],
       [18,  3,  1]])

In [57]:
data[::2, -1]

array([0, 1])

In [58]:
data[-2:, -2:]

array([[ 3,  1],
       [10,  0]])

In [61]:
data[[1, 2]]

array([[ 5, 13,  5],
       [18,  3,  1]])

In [62]:
data[:, [True, True, False]] # логическая индексация

array([[26,  1],
       [ 5, 13],
       [18,  3],
       [13, 10]])

In [63]:
# перемешать строки в случайном порядке
np.random.permutation(data)

array([[ 5, 13,  5],
       [18,  3,  1],
       [26,  1,  0],
       [13, 10,  0]])

In [64]:
idxs = np.random.permutation(np.arange(data.shape[0]))
data[idxs]

array([[13, 10,  0],
       [ 5, 13,  5],
       [26,  1,  0],
       [18,  3,  1]])

In [65]:
data[::-1]

array([[13, 10,  0],
       [18,  3,  1],
       [ 5, 13,  5],
       [26,  1,  0]])

In [66]:
data

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0]])

### Объединение массивов

In [67]:
new_data = np.array([[14, 4, 1], [1, 11, 9]])

In [68]:
new_data

array([[14,  4,  1],
       [ 1, 11,  9]])

In [70]:
long_data = np.vstack((data, new_data))

In [71]:
long_data

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0],
       [14,  4,  1],
       [ 1, 11,  9]])

In [72]:
np.hstack((data, data))

array([[26,  1,  0, 26,  1,  0],
       [ 5, 13,  5,  5, 13,  5],
       [18,  3,  1, 18,  3,  1],
       [13, 10,  0, 13, 10,  0]])

In [73]:
np.concatenate((data, new_data), axis=0)

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0],
       [14,  4,  1],
       [ 1, 11,  9]])

np.hstack((data, new_data)) # ошибка

In [80]:
np.hstack((long_data, long_data.sum(axis=1).reshape(6, 1)))

array([[26,  1,  0, 27],
       [ 5, 13,  5, 23],
       [18,  3,  1, 22],
       [13, 10,  0, 23],
       [14,  4,  1, 19],
       [ 1, 11,  9, 21]])

In [76]:
long_data.shape

(6, 3)

In [77]:
long_data.sum(axis=1).shape

(6,)

In [ ]:
##### newaxis

In [81]:
sums = long_data.sum(axis=1)

In [82]:
sums

array([27, 23, 22, 23, 19, 21])

In [83]:
sums.shape

(6,)

In [84]:
sums[:, np.newaxis]

array([[27],
       [23],
       [22],
       [23],
       [19],
       [21]])

In [85]:
sums[:, np.newaxis].shape

(6, 1)

In [86]:
sums[np.newaxis, :].shape

(1, 6)

##### Broadcasting

In [87]:
long_data

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0],
       [14,  4,  1],
       [ 1, 11,  9]])

In [91]:
long_data / sums[:, np.newaxis]

array([[0.96296296, 0.03703704, 0.        ],
       [0.2173913 , 0.56521739, 0.2173913 ],
       [0.81818182, 0.13636364, 0.04545455],
       [0.56521739, 0.43478261, 0.        ],
       [0.73684211, 0.21052632, 0.05263158],
       [0.04761905, 0.52380952, 0.42857143]])

In [90]:
long_data.shape, sums.shape

((6, 3), (6,))

In [ ]:
# Задача: создать таблицу умножения до 9

In [92]:
numbers = np.arange(10)

In [93]:
numbers[:, np.newaxis] * numbers[np.newaxis, :]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

### Binary arrays

In [94]:
bin_array = np.array([True, False, True, False])

In [95]:
np.all(bin_array)

False

In [96]:
np.any(bin_array)

True

In [97]:
np.sum(bin_array)

2

Сколько вопросов, у которых ответов нет больше, чем ответов да?

In [98]:
long_data

array([[26,  1,  0],
       [ 5, 13,  5],
       [18,  3,  1],
       [13, 10,  0],
       [14,  4,  1],
       [ 1, 11,  9]])

In [99]:
yes = long_data[:, 0]
no = long_data[:, 1]

In [101]:
yes, no

(array([26,  5, 18, 13, 14,  1]), array([ 1, 13,  3, 10,  4, 11]))

In [102]:
yes < no

array([False,  True, False, False, False,  True])

In [103]:
np.sum(yes<no)

2

Верно ли, что на все вопросы ответов да больше, чем ответов "воздерживаюсь"?

In [104]:
skip = long_data[:, -1]
np.all(yes > skip)

False