### Classes

In [7]:
class MaxCounter:
    def __init__(self):
        self.current_max = -10**10
    
    def add_number(self, number):
        if number > self.current_max:
            self.current_max = number
            
    def print_max(self):
        print("Max:", self.current_max)

In [8]:
counter = MaxCounter()

In [9]:
counter.current_max

-10000000000

In [10]:
counter.add_number(10)
counter.add_number(7)

In [11]:
counter.current_max

10

In [12]:
counter.print_max()

Max: 10


In [15]:
counter2 = MaxCounter()
counter2.add_number(-5)
counter2.add_number(1)
counter2.add_number(174)
counter2.print_max()

Max: 174


In [18]:
counter2.add_number(1111)
counter2.print_max()

Max: 1111


In [14]:
counter.print_max()

Max: 10


In [19]:
class Concat:
    def __init__(self):
        self.li = []
        
    def add_string(self, new_string):
        self.li.append(new_string)
        
    def print_string(self):
        print(" ".join(self.li))
        # print(*self.li)

In [29]:
class Concat:
    def __init__(self):
        self.current_str = ""
        
    def add_string(self, new_string):
        if self.current_str == "":
            self.current_str = new_string
        else:
            self.current_str = self.current_str + " " + new_string
        
    def print_string(self):
        print(self.current_str)

In [30]:
concat = Concat()
concat.add_string("hello")
concat.add_string("world")

In [28]:
concat.print_string()

### Scikit learn

In [31]:
import sklearn

In [34]:
from sklearn.neighbors import KNeighborsRegressor

In [35]:
knn = KNeighborsRegressor()

In [36]:
knn.fit

<bound method SupervisedFloatMixin.fit of KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=5, p=2,
          weights='uniform')>

##### importing data

In [37]:
from sklearn.datasets import load_boston

In [38]:
boston = load_boston()

In [39]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [40]:
print(boston.DESCR)

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [43]:
boston.data.shape, boston.target.shape

((506, 13), (506,))

In [ ]:
boston.target

In [45]:
X = boston.data
Y = boston.target

In [47]:
knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(X, Y) # training data
knn.predict(X) # predictions on training data

array([23.09, 21.32, 23.68, 24.01, 23.47, 25.08, 21.6 , 18.3 , 17.65,
       20.09, 18.3 , 21.41, 23.  , 21.89, 28.74, 22.18, 27.17, 21.12,
       19.22, 24.38, 15.82, 19.56, 19.27, 19.32, 19.27, 19.33, 22.1 ,
       19.33, 19.08, 24.01, 19.14, 16.51, 17.5 , 19.14, 18.5 , 24.7 ,
       22.19, 25.2 , 26.4 , 33.81, 34.9 , 23.28, 23.28, 23.12, 21.7 ,
       20.61, 20.61, 21.38, 21.8 , 24.35, 25.59, 27.68, 25.19, 25.19,
       29.3 , 38.73, 25.07, 37.31, 23.27, 23.99, 21.69, 35.6 , 22.67,
       24.45, 28.92, 26.  , 26.13, 26.55, 22.58, 24.41, 27.13, 27.13,
       27.13, 26.56, 21.91, 21.43, 25.69, 21.43, 20.87, 22.01, 24.75,
       25.9 , 24.93, 26.14, 22.95, 22.82, 22.95, 23.13, 23.61, 25.56,
       25.1 , 23.08, 26.52, 26.65, 31.58, 25.83, 24.89, 23.53, 25.58,
       25.54, 20.53, 20.89, 17.16, 19.98, 19.98, 20.5 , 19.98, 19.98,
       20.5 , 19.98, 21.49, 19.08, 18.15, 17.78, 19.61, 19.95, 18.77,
       18.74, 19.22, 18.77, 29.58, 23.18, 24.01, 23.28, 23.28, 25.69,
       22.99, 17.2 ,

##### split dataset

In [48]:
from sklearn.model_selection import train_test_split

In [53]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.5)

In [54]:
X.shape, X_train.shape, X_test.shape

((506, 13), (253, 13), (253, 13))

In [56]:
### сделать предсказания для Y_test
knn = KNeighborsRegressor(n_neighbors=10)
knn.fit(X_train, Y_train) # training data
Y_test_pred = knn.predict(X_test) # predictions on testing data

In [57]:
Y_test.shape, Y_test_pred.shape

((253,), (253,))

In [58]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [59]:
mean_squared_error(Y_test, Y_test_pred)

51.663250592885376

In [60]:
mean_absolute_error(Y_test, Y_test_pred)

5.06102766798419

In [61]:
r2_score(Y_test, Y_test_pred)

0.4013474393996964

In [63]:
Y_train_pred = knn.predict(X_train)

In [64]:
mean_absolute_error(Y_train, Y_train_pred)

4.323596837944663

In [65]:
r2_score(Y_train, Y_train_pred)

0.53230562953854

In [66]:
import numpy as np

In [72]:
class MyScaler:
    def fit(self, X_train):
        # save min and max inside class
        self.mins = X_train.min(axis=0) # вектор длины число признаков
        self.maxs = X_train.max(axis=0)
    
    def transform(self, X):
        # apply tranformation
        X_transformed = (X - self.mins[np.newaxis, :]) / (self.maxs-self.mins)[np.newaxis, :]
        return X_transformed

In [73]:
scaler = MyScaler()
scaler.fit(X_train)
X_test_tr = scaler.transform(X_test)

In [74]:
X_test[:2]

array([[2.4980e-02, 0.0000e+00, 1.8900e+00, 0.0000e+00, 5.1800e-01,
        6.5400e+00, 5.9700e+01, 6.2669e+00, 1.0000e+00, 4.2200e+02,
        1.5900e+01, 3.8996e+02, 8.6500e+00],
       [2.8960e-01, 0.0000e+00, 9.6900e+00, 0.0000e+00, 5.8500e-01,
        5.3900e+00, 7.2900e+01, 2.7986e+00, 6.0000e+00, 3.9100e+02,
        1.9200e+01, 3.9690e+02, 2.1140e+01]])

In [75]:
X_test_tr[:2]

array([[1.78942472e-04, 0.00000000e+00, 5.24193548e-02, 0.00000000e+00,
        2.67634855e-01, 5.17449375e-01, 5.70362473e-01, 5.34293380e-01,
        0.00000000e+00, 4.47418738e-01, 3.51063830e-01, 9.82500378e-01,
        2.07140659e-01],
       [3.15329907e-03, 0.00000000e+00, 3.38343109e-01, 0.00000000e+00,
        4.06639004e-01, 2.69711331e-01, 7.11087420e-01, 1.70785645e-01,
        2.17391304e-01, 3.88145315e-01, 7.02127660e-01, 1.00000000e+00,
        5.91566636e-01]])